### ISSUE TITLE
Generated process graphs are still v0.4?

### ISSUE THREAD

**Issue by christophfriedrich** [Open-EO/openeo-python-client#156]
Hi, I'm not sure whether I'm doing all this correctly as I'm no Python expert, but anyway...

For Deliverable 35, I need v1.0 process graphs for the EVI use case for all backends. There is code in the [D22 repository](https://github.com/Open-EO/openeo-D22) with which v0.4 process graphs were created for all backends for Deliverable 22. I thought, if I use the same code, but with the latest python client, I should easily receive v1.0 process graphs. I tried that (see below for details), but the GEE backend (which was the first I tried) refused the graph. I thought this was a backend-side error and opened Open-EO/openeo-js-processgraphs#9, but Matthias said that it's indeed the process graph which is wrong, because it has v0.4 format... (see the linked issue for details)

**Does the client not output valid v1.0 graphs yet??**

What I did:
1. Clone this repo
2. Run `christoph@gin-friedrich:~/dev/openeo-python-client$ pip install -e .[dev]` which failed
3. Comment out `openeo-udf` from the `setup.py` because it somehow couldn't be found
4. Run the command from 2. again, now it worked
3. Slightly adapt code from D22:
   - move GEE to the top of the `backends` array in _main.py_
   - change the backend URL to the v1.0 instance of GEE in _wwu\_gee.py_
   - add a line that prints the generated proces graph: `print(json.dumps(min_evi_stretched.graph))` just before the last line of _wwu\_gee.py_
6. Run `christoph@gin-friedrich:~/dev/openeo-D22$ python3.6 main.py`

Output:
```
Processing job from backend: WWU_GEE - L1C of ['L1C', 'L2A']
{"loadcollection1": {"process_id": "load_collection", "arguments": {"id": "COPERNICUS/S2", "spatial_extent": {"west": 11.279182434082033, "east": 11.406898498535158, "north": 46.522729291844286, "south": 46.464349400461145, "crs": "EPSG:4326"}, "temporal_extent": ["2018-06-04T00:00:00Z", "2018-06-23T00:00:00Z"], "bands": ["B8", "B4", "B2"]}, "result": false}, "reduce3": {"process_id": "reduce", "arguments": {"data": {"from_node": "loadcollection1"}, "dimension": "bands", "reducer": {"callback": {"arrayelement8": {"process_id": "array_element", "arguments": {"data": {"from_argument": "data"}, "index": 0}, "result": false}, "arrayelement9": {"process_id": "array_element", "arguments": {"data": {"from_argument": "data"}, "index": 1}, "result": false}, "product7": {"process_id": "product", "arguments": {"data": [{"from_node": "subtract3"}, 2.5]}, "result": false}, "subtract3": {"process_id": "subtract", "arguments": {"data": [{"from_node": "arrayelement8"}, {"from_node": "arrayelement9"}]}, "result": false}, "arrayelement10": {"process_id": "array_element", "arguments": {"data": {"from_argument": "data"}, "index": 0}, "result": false}, "arrayelement11": {"process_id": "array_element", "arguments": {"data": {"from_argument": "data"}, "index": 1}, "result": false}, "arrayelement12": {"process_id": "array_element", "arguments": {"data": {"from_argument": "data"}, "index": 2}, "result": false}, "product8": {"process_id": "product", "arguments": {"data": [{"from_node": "arrayelement11"}, 6.0]}, "result": false}, "product9": {"process_id": "product", "arguments": {"data": [{"from_node": "arrayelement12"}, 7.5]}, "result": false}, "subtract4": {"process_id": "subtract", "arguments": {"data": [{"from_node": "sum4"}, {"from_node": "product9"}]}, "result": false}, "sum4": {"process_id": "sum", "arguments": {"data": [{"from_node": "arrayelement10"}, {"from_node": "product8"}]}, "result": false}, "sum5": {"process_id": "sum", "arguments": {"data": [{"from_node": "subtract4"}, 10000]}, "result": false}, "divide1": {"process_id": "divide", "arguments": {"data": [{"from_node": "product7"}, {"from_node": "sum5"}]}, "result": true}}}}, "result": false}, "reduce4": {"process_id": "reduce", "arguments": {"data": {"from_node": "reduce3"}, "dimension": "t", "reducer": {"callback": {"r1": {"arguments": {"data": {"from_argument": "data"}}, "process_id": "min", "result": true}}}}, "result": false}, "apply1": {"process_id": "apply", "arguments": {"data": {"from_node": "reduce4"}, "process": {"callback": {"unary": {"arguments": {"inputMin": -1, "inputMax": 1, "outputMin": 0, "outputMax": 255, "x": {"from_argument": "x"}}, "process_id": "linear_scale_range", "result": true}}}}, "result": false}}
Traceback (most recent call last):
  File "main.py", line 57, in <module>
    wwu_gee_script(data_item, output_filename)
  File "/home/christoph/dev/openeo-D22/scripts/wwu_gee.py", line 54, in wwu_gee_script
    output = min_evi_stretched.download(output_filename,format="png")
  File "/home/christoph/dev/openeo-python-client/openeo/rest/imagecollectionclient.py", line 1021, in download
    return self.session.download(newcollection.graph, outputfile)
  File "/home/christoph/dev/openeo-python-client/openeo/rest/connection.py", line 750, in download
    r = self.post(path="/result", json=request, stream=True, timeout=1000)
  File "/home/christoph/dev/openeo-python-client/openeo/rest/connection.py", line 162, in post
    return self.request("post", path=path, json=json, **kwargs)
  File "/home/christoph/dev/openeo-python-client/openeo/rest/connection.py", line 110, in request
    self._raise_api_error(resp)
  File "/home/christoph/dev/openeo-python-client/openeo/rest/connection.py", line 141, in _raise_api_error
    raise exception
openeo.rest.connection.OpenEoApiError: [500] ReferencedNodeMissing: Referenced node 'subtract3' doesn't exist.
```

I verified I have the latest version running by setting up a `versioncheck.py` which contains:
```
from openeo._version import __version__
print(__version__)
```
and calling it from the same shell with `python3.6 versioncheck.py` and that outputs `0.4.6a1` as expected.

**Comment by soxofaan** [comment]
Sorry for late answer, the notification for this one was hidden in pile of other notifications.

The python client will generate a 1.0 compatible process graph when using a connection to a 1.0 backend.
So if you use these D22 scripts with a recent client, but against a 0.4 backend, you will still get 0.4-style process graphs.

**Comment by soxofaan** [comment]
> change the backend URL to the v1.0 instance of GEE in wwu_gee.py

apparently you *did* update the backend url , so that is not the issue

what I do see however in the wwu_gee.py script is that i creates a data cube like this:
```python
    s2_radiometry = ImageCollectionClient.load_collection(
                        session=session,
```

This `ImageCollectionClient` is a 0.4-only implementation

The proper way to do load_collection in a API version aware way is 
```python
session.load_collection(...
```

**Comment by soxofaan** [comment]
This approach should work

```python
s2_radiometry = con.load_collection(collection_id, temporal_extent=temporal_extent, spatial_extent=spatial_extent, bands=spectral_extent)

B02 = s2_radiometry.band(2)
B04 = s2_radiometry.band(1)
B08 = s2_radiometry.band(0)

evi_cube = (2.5 * (B08 - B04)) / ((B08 + 6.0 * B04 - 7.5 * B02) + 10000)

min_evi = evi_cube.min_time()


from openeo.processes import linear_scale_range

min_evi_stretched = min_evi.apply(process=lambda data: data.linear_scale_range(inputMin=-1, inputMax=1, outputMin=0, outputMax=255))

```

**Comment by soxofaan** [comment]
I will close this now

feel free to reopen when necessary
