### ISSUE TITLE
Negative bbox coördinate results in 400 error

### ISSUE THREAD

**Issue by Jaapel** [Open-EO/openeo-python-client#227]
When using a bounding box with large negative values, I get a 400 error:
`OpenEoApiError: [400] unknown: requirement failed: Range bounds must be ordered, but 1317642205727285687 > 17643812314676`

Minimal example to reproduce:
```python
from openeo import connect, Connection
from openeo.rest.datacube import DataCube

vito_dev_url: str = "https://openeo-dev.vito.be/openeo/1.0/"
con: Connection = connect(vito_dev_url)
con.authenticate_oidc(provider_id="egi")

out_dir = pathlib.Path("output")
out_dir.mkdir(parents=True, exist_ok=True)

spain_bbox = {"west": -9.39288367353, "east": 3.03948408368, "south": 35.946850084, "north": 43.7483377142, "crs": "EPSG:4326"}
small_bbox = {"west": -0.01, "east": 0.01, "south": -0.01, "north": 0.01, "crs": "EPSG:4326"}
temporal_extent: List[str] = ["2021-04-26", "2021-04-30"]

collection = ("LANDSAT8_L2", ["B06", "B05", "B03"])
dc: DataCube = con.load_collection(
        collection_id=collection[0],
        spatial_extent=spain_bbox,
        temporal_extent=temporal_extent,
        bands=collection[1]
    )

dc.download(out_dir / "test.tiff", format="GTiff")
```

This code works when setting the keys to something positive like 0. Weirdly enough, when using the smaller bbox with negative values, the code works. Any ideas?

**Comment by soxofaan** [comment]
I didn't have time yet to dive deeper at the moment, but isolated these related back-end logs:

```
[2021-09-13 14:57:48,447] ERROR in openeo_driver.views: An error occurred while calling o1306.datacube_seq.
: java.lang.IllegalArgumentException: requirement failed: Range bounds must be ordered, but 1317642205727285687 > 17643812314676
	at org.locationtech.sfcurve.zorder.ZRange.<init>(ZRange.scala:20)
	at org.locationtech.sfcurve.zorder.ZRange$.apply(ZRange.scala:38)
	at org.openeo.geotrelliscommon.zcurve.SfCurveZSpaceTimeKeyIndex.indexRanges(SfCurveZSpaceTimeKeyIndex.scala:57)
	at org.openeo.geotrelliscommon.zcurve.SfCurveZSpaceTimeKeyIndex.indexRanges(SfCurveZSpaceTimeKeyIndex.scala:54)
	at org.openeo.geotrelliscommon.package$SpaceTimeByMonthPartitioner$.indexRanges(package.scala:48)
	at geotrellis.spark.partition.SpacePartitioner.<init>(SpacePartitioner.scala:34)
	at org.openeo.geotrellissentinelhub.PyramidFactory.datacube_seq(PyramidFactory.scala:257)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
...
  File ".../site-packages/openeogeotrellis/layercatalog.py", line 371, in load_collection
    pyramid = sentinel_hub_pyramid()
  File ".../site-packages/openeogeotrellis/layercatalog.py", line 310, in sentinel_hub_pyramid
    shub_band_names, metadata_properties(), datacubeParams) if single_level
  File "py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1257, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "py4j-0.10.7-src.zip/py4j/protocol.py", line 328, in get_return_value
    format(target_id, ".", name), value)
py4j.protocol.Py4JJavaError: An error occurred while calling o1306.datacube_seq.
: java.lang.IllegalArgumentException: requirement failed: Range bounds must be ordered, but 1317642205727285687 > 17643812314676
```

maybe this rings a bell for @jdries  already
