### ISSUE TITLE
lint-and-tests build fails

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-python-client#367]
Almost together with #366,  the lint-and-tests (https://github.com/Open-EO/openeo-python-client/blob/dcfc03eb10612fc83e4e16c2d7d99e9cc05647e1/.github/workflows/lint-and-test.yml) build also started failing with
```
Run # stop the build if there are Python syntax errors or undefined names
  # stop the build if there are Python syntax errors or undefined names
  flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
  # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
  flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.7.15/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.7.15/x64/lib
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.15/x64/bin/flake8", line 8, in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages/flake8/main/cli.py", line 22, in main
    app.run(argv)
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages/flake8/main/application.py", line 363, in run
    self._run(argv)
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages/flake8/main/application.py", line 350, in _run
    self.initialize(argv)
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages/flake8/main/application.py", line 330, in initialize
    self.find_plugins(config_finder)
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages/flake8/main/application.py", line 153, in find_plugins
    self.check_plugins = plugin_manager.Checkers(local_plugins.extension)
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages/flake8/plugins/manager.py", line 357, in __init__
    self.namespace, local_plugins=local_plugins
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages/flake8/plugins/manager.py", line 238, in __init__
    self._load_entrypoint_plugins()
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages/flake8/plugins/manager.py", line 254, in _load_entrypoint_plugins
    eps = importlib_metadata.entry_points().get(self.namespace, ())
AttributeError: 'EntryPoints' object has no attribute 'get'
Error: Process completed with exit code 1.
```

**Comment by soxofaan** [comment]
build starts failing with this commit 75d9e0eac4920b2e28a9837b5f3cf6b3bc33638a  but I haven't figured out how that would influence the flak8 run

**Comment by soxofaan** [comment]
this seems to be related: https://github.com/PyCQA/flake8/issues/1701

**Comment by soxofaan** [comment]
Last build that works (https://github.com/Open-EO/openeo-python-client/actions/runs/3957084984/jobs/6777024697) sets up this env (from logs):
```
# from `pip install flake8 pytest`:
Successfully installed ...  flake8-5.0.4 importlib-metadata-4.2.0 ... mccabe-0.7.0 ... pycodestyle-2.9.1 pyflakes-2.5.0 ...
# from `pip install .[dev]`:
# no flake related installs
```

First failing build (https://github.com/Open-EO/openeo-python-client/actions/runs/3957403589/jobs/6777732462):
```
# from `pip install flake8 pytest`:
Successfully installed ... flake8-5.0.4 importlib-metadata-4.2.0 ... mccabe-0.7.0 ... pycodestyle-2.9.1 pyflakes-2.5.0 ...
# from `pip install .[dev]`:
Successfully installed ... flake8-3.9.2 ... importlib-metadata-6.0.0 ... mccabe-0.6.1 ... pycodestyle-2.7.0 pyflakes-2.3.1...
```

So second pip install triggers installation of old flake8 for some reason
Not sure why

**Comment by soxofaan** [comment]
seems fixed now, so that's good

However, still confused what was going on

**Comment by soxofaan** [comment]
Checking the logs again of failing build: 
for some reason, pip decided to downgrade flake8 to a pretty old version `3.9.2`
```
Collecting flake8
  Downloading flake8-5.0.3-py2.py3-none-any.whl (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.9/61.9 kB 18.6 MB/s eta 0:00:00
Requirement already satisfied: pycodestyle<2.10.0,>=2.9.0 in /opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages (from flake8->openeo==0.14.0a1) (2.9.1)
Requirement already satisfied: pyflakes<2.6.0,>=2.5.0 in /opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/site-packages (from flake8->openeo==0.14.0a1) (2.5.0)
  Downloading flake8-5.0.2-py2.py3-none-any.whl (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.9/61.9 kB 19.7 MB/s eta 0:00:00
  Downloading flake8-5.0.1-py2.py3-none-any.whl (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.7/61.7 kB 20.1 MB/s eta 0:00:00
  Downloading flake8-5.0.0-py2.py3-none-any.whl (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.7/61.7 kB 20.0 MB/s eta 0:00:00
  Downloading flake8-4.0.1-py2.py3-none-any.whl (64 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.1/64.1 kB 17.0 MB/s eta 0:00:00
Collecting pycodestyle<2.9.0,>=2.8.0
  Downloading pycodestyle-2.8.0-py2.py3-none-any.whl (42 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.1/42.1 kB 11.9 MB/s eta 0:00:00
Collecting flake8
  Downloading flake8-4.0.0-py2.py3-none-any.whl (64 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.1/64.1 kB 19.0 MB/s eta 0:00:00
  Downloading flake8-3.9.2-py2.py3-none-any.whl (73 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.1/73.1 kB 27.5 MB/s eta 0:00:00
```

Confusingly adding explicit constraint `"flake8>=5.0.0"` in 796398fdb018a4e895afc40a978937fe2cfe80a8 was enough as a fix


oh well
