### ISSUE TITLE
Erorr [MissingProduct] in the collection ‘SENTINEL2_L2A’

### ISSUE THREAD

**Issue by mo7yasser** [Open-EO/openeo-python-client#498]
```
import openeo

connection = openeo.connect("https://openeo.dataspace.copernicus.eu")

# connection.authenticate_basic(username,password)
connection.authenticate_oidc()


loadco1 = connection.load_collection(collection_id = "SENTINEL2_L2A", 
                                    spatial_extent = {
                                        "west": 34.95835721872348, 
                                        "east": 35.716862053317165, 
                                        "south": 9.911686169872496, 
                                        "north": 11.323739028869284}, 
                                    temporal_extent = ["2023-11-01", "2023-11-08"], 
                                    bands = ["SCL"])

savere1 = loadco1.save_result(format = "GTIFF")
result = connection.execute(savere1)
```

The code raise this error 

```
Authenticated using refresh token.
Preflight process graph validation raised: [MissingProduct] Tile 'S2B_MSIL2A_20231105T080029_N0509_R035_T36PYT_20231105T102738' in collection 'SENTINEL2_L2A' is not available. [MissingProduct] Tile 'S2B_MSIL2A_20231105T080029_N0509_R035_T36PYS_20231105T102738' in collection 'SENTINEL2_L2A' is not available. [MissingProduct] Tile 'S2B_MSIL2A_20231105T080029_N0509_R035_T36PYR_20231105T102738' in collection 'SENTINEL2_L2A' is not available.
Traceback (most recent call last):
  File "C:\Users\mohamed.yasser\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mohamed.yasser\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mohamed.yasser\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mohamed.yasser\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\GERDProject_Automation\codeV3\testOPEO.py", line 42, in <module>
    result = connection.execute(savere1)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mohamed.yasser\AppData\Local\Programs\Python\Python311\Lib\site-packages\openeo\rest\connection.py", line 1578, in execute
    ).json()  # TODO: only do JSON decoding when mimetype is actually JSON?
      ^^^^^^
  File "C:\Users\mohamed.yasser\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

The error message suggests that there is a missing product in the collection ‘SENTINEL2_L2A’

**Comment by soxofaan** [comment]
That `Preflight process graph validation raised: [MissingProduct] Tile ...` is just a warning you can ignore. The root cause of that is being handled under https://github.com/Open-EO/openeo-geopyspark-driver/issues/566

the actual exception is about this part of your snippet:
```
savere1 = loadco1.save_result(format = "GTIFF")
result = connection.execute(savere1)
```

`connection.execute()` assumes that the result is JSON and tries to decode that, while you explicitly request geotiff here, which obviously doesn't work


instead use `savere1.download("result.tiff")`


By the way: I hope this is not your real password you are sharing publicly here (otherwise I would recommend changing it)
```
username = "eodd.egsa@gmail.com"
password = "Egsa@@@@2023"
```
