### ISSUE TITLE
Internal: Server error: KazooTimeoutError('Connection time-out')

### ISSUE THREAD

**Issue by marioeo94** [Open-EO/openeo-python-client#563]
Good morning, 

I was testing the openEO library in Python, so as to download some data, but I obtained an error (KazooTimeoutError) and I do not why. 

This is the code I used: 

import openeo
import os 

# Set proxy settings as environment variables
#os.environ['HTTP_PROXY'] = 'http://xxxx.xxx.xx:yyyy'
#os.environ['HTTPS_PROXY'] = 'http://xxxx.xxx.xx:yyyy'

connection = openeo.connect("openeo.dataspace.copernicus.eu")
connection.authenticate_oidc()

# Main directory where this Python script is located
base_dir = os.path.dirname(__file__)

# Directory where outputs are saved
output_image = os.path.join(base_dir, 'OUTPUT')

# Main directory where this Python script is located
base_dir = os.path.dirname(__file__)

# Directory where outputs are saved
output_image = os.path.join(base_dir, 'OUTPUT');

cube = connection.load_collection(
    "SENTINEL2_L2A",
    spatial_extent={"west": 3.75, "east": 4.08, "south": 51.29, "north": 51.39},
    temporal_extent=["2022-05-07", "2022-05-14"],
    bands=["B04", "B03", "B02"],
)

cube.download(output_image + os.path.sep + 'test.tiff')

# Error

And the error is the following: 

Authorized successfully
Authenticated using device code flow.
Traceback (most recent call last):
  File "e:\test_openeo\test.py", line 33, in <module>
    cube.download(output_image + os.path.sep + 'test.tiff')
  File "C:\Users\Down\miniconda3\envs\openeo\Lib\site-packages\openeo\rest\datacube.py", line 2118, in download
    return self._connection.download(cube.flat_graph(), outputfile, validate=validate)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Down\miniconda3\envs\openeo\Lib\site-packages\openeo\rest\connection.py", line 1585, in download
    response = self.post(
               ^^^^^^^^^^
  File "C:\Users\Down\miniconda3\envs\openeo\Lib\site-packages\openeo\rest\connection.py", line 249, in post
    return self.request("post", path=path, json=json, allow_redirects=False, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Down\miniconda3\envs\openeo\Lib\site-packages\openeo\rest\connection.py", line 788, in request
    return _request()
           ^^^^^^^^^^
  File "C:\Users\Down\miniconda3\envs\openeo\Lib\site-packages\openeo\rest\connection.py", line 781, in _request
    return super(Connection, self).request(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Down\miniconda3\envs\openeo\Lib\site-packages\openeo\rest\connection.py", line 187, in request
    self._raise_api_error(resp)
  File "C:\Users\Down\miniconda3\envs\openeo\Lib\site-packages\openeo\rest\connection.py", line 207, in _raise_api_error
    raise OpenEoApiError(
openeo.rest.OpenEoApiError: [500] Internal: Server error: KazooTimeoutError('Connection time-out') (ref: r-24051087d2734a57ad57ca85238c1ea9)

Many thanks in advance for your help.

**Comment by jdries** [comment]
Hi, this is not a client issue, but a server issue, and should now be solved, please reopen if still a problem!
